
name: build project and upload as artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update apt repos
      run: sudo apt update -y
    - name: install cmake
      run: sudo apt install make wget gcc g++ -y
    - name: From this point idk what am I doing
      run:
        wget https://ftp.gnu.org/gnu/ncurses/ncurses-6.4.tar.gz
        tar xvzf ncurses-6.4.tar.gz
        cd ncurses-*
        sudo ./configure
        sudo make
        cd ..
        sudo apt install libncurses-dev
        g++ src/*.cpp src/core/*.cpp -lncurses -static-libstdc++ -static -static-libgcc /usr/lib/x86_64-linux-gnu/libncurses.a /usr/lib/x86_64-linux-gnu/libtinfo.a -o main
    - name: archive resulting executable
      uses: actions/upload-artifact@v4
      with:
          name: main_executable
          path: main
